### ISSUE TITLE
Allow to choose search result other than the first one

### ISSUE THREAD

**Issue by steeph-k** [0zz4r/bashflix#14]
I'll just make a few feature request I find useful. Feel free to ignore them for now. If I continue to find them useful, I'll add them myself.

Often the search results contain a variety of good results but the first one is not the actual movie I'm looking for. In these cases it would be useful to be able to run bashflix again with the same search term and add the number of the desired torrent. I'm not sure how this would be done best. Maybe by checking whether the second or third argument is a number and if it is, treat it as a search result selection.

**Comment by FriendlyGecko** [comment]
Try using this patch I made based on a couple changes I made to it. Let me know how it works. I don't really use bashflix, but I like tweaking things. You will have to rename the file to bashflix.patch (github doesn't allow patch files to be uploaded) and use it to patch my changes to your bashflix script. My changes make so that you can use it regularly and it will auto-select the first or you include the option -q (stands for query, might consider changing it to -s for clarity in the code).

[bashflix.txt](https://github.com/0zz4r/bashflix/files/6489351/bashflix.txt)

**Comment by FriendlyGecko** [comment]
Resolved via #20

**Comment by 0zz4r** [comment]
^
